### ISSUE TITLE
对shadowsocks协议的outbound的setting中的method预期值类型设定错误

### ISSUE THREAD

**Issue by lychichem** [EHfive/v2ray-jsonschema#1]
文档要求的是string，schema预期的是object

**Comment by EHfive** [comment]
Yet another custom unmarshaling https://github.com/v2fly/v2ray-core/blob/458db3954f76bbf7ce621a24151d9d5469d8b6fb/proxy/shadowsocks/simplified/config.go#L15-L27 needs to be manually handled..

**Comment by lychichem** [comment]
加密方式目前的枚举值仍然是错的，不能用下划线`_`，而应使用连接符`-`

**Comment by EHfive** [comment]
No, both formats are valid. I just not bother to add another manually written schema.

https://github.com/v2fly/v2ray-core/blob/458db3954f76bbf7ce621a24151d9d5469d8b6fb/proxy/shadowsocks/config.go#L213-L226

> 加密方式目前的枚举值仍然是错的

And stop saying it's "wrong" just because the documentation suggests something else. The V2Ray documentation is not a specification but just a lesser reflection to actual code.

Also PR is welcome if what you really want is just to have those dashed version of enums to show up in schema.
